export const product = [
  {
    id: 209,
    display_id: 8,
    owner: 1079,
    name: "New Product",
    category: "The god of War",
    characteristics: "New Product Characteristics",
    features: "",
    brand: "New Product Brand",
    sku: [
      {
        id: 248,
        selling_price: 54,
        max_retail_price: 44,
        amount: 33,
        unit: "kg",
        quantity_in_inventory: 0,
        product: 209,
      },
      {
        id: 247,
        selling_price: 32,
        max_retail_price: 32,
        amount: 33,
        unit: "kg",
        quantity_in_inventory: 0,
        product: 209,
      },
      {
        id: 246,
        selling_price: 23,
        max_retail_price: 21,
        amount: 22,
        unit: "kg",
        quantity_in_inventory: 1,
        product: 209,
      },
    ],
    updated_on: "2024-05-24T12:46:41.995873Z",
    adding_date: "2024-05-24T12:46:41.995828Z",
  },
  {
    id: 210,
    display_id: 9,
    owner: 1080,
    name: "Second Product",
    category: "Fantasy",
    characteristics: "Second Product Characteristics",
    features: "",
    brand: "Second Product Brand",
    sku: [
      {
        id: 249,
        selling_price: 49,
        max_retail_price: 39,
        amount: 29,
        unit: "kg",
        quantity_in_inventory: 0,
        product: 210,
      },
      {
        id: 250,
        selling_price: 35,
        max_retail_price: 35,
        amount: 35,
        unit: "kg",
        quantity_in_inventory: 0,
        product: 210,
      },
      {
        id: 251,
        selling_price: 28,
        max_retail_price: 25,
        amount: 24,
        unit: "kg",
        quantity_in_inventory: 2,
        product: 210,
      },
    ],
    updated_on: "2024-05-30T09:12:00.000000Z",
    adding_date: "2024-05-30T09:12:00.000000Z",
  },
  {
    id: 211,
    display_id: 10,
    owner: 1081,
    name: "Third Product",
    category: "Sci-Fi",
    characteristics: "Third Product Characteristics",
    features: "",
    brand: "Third Product Brand",
    sku: [
      {
        id: 252,
        selling_price: 65,
        max_retail_price: 55,
        amount: 45,
        unit: "kg",
        quantity_in_inventory: 0,
        product: 211,
      },
      {
        id: 253,
        selling_price: 40,
        max_retail_price: 40,
        amount: 40,
        unit: "kg",
        quantity_in_inventory: 0,
        product: 211,
      },
      {
        id: 254,
        selling_price: 30,
        max_retail_price: 28,
        amount: 27,
        unit: "kg",
        quantity_in_inventory: 3,
        product: 211,
      },
    ],
    updated_on: "2024-05-30T09:15:00.000000Z",
    adding_date: "2024-05-30T09:15:00.000000Z",
  },
];
